FROM golang:1.20

RUN apt-get update && apt install -y zsh
RUN sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
RUN chsh -s $(which zsh)

RUN go install -v github.com/cweill/gotests/gotests@v1.6.0
RUN go install -v github.com/fatih/gomodifytags@v1.16.0
RUN go install -v github.com/josharian/impl@v1.1.0
RUN go install -v github.com/go-delve/delve/cmd/dlv@latest
RUN go install -v honnef.co/go/tools/cmd/staticcheck@latest
RUN go install -v golang.org/x/tools/gopls@latest

RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN go install github.com/vektra/mockery/v2@v2.20.0
RUN go install golang.org/x/vuln/cmd/govulncheck@latest

WORKDIR /code

COPY ["go.mod", "go.sum", "./"]

RUN go mod download