FROM golang:1.20

RUN go install -v golang.org/x/tools/gopls@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN go install github.com/vektra/mockery/v2@v2.20.0

WORKDIR /code

COPY ["go.mod", "go.sum", "./"]

RUN go mod download