// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks_domain

import (
	context "context"
	domain "your-accounts-api/users/domain"

	mock "github.com/stretchr/testify/mock"

	persistent "your-accounts-api/shared/domain/persistent"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// ExistsByExample provides a mock function with given fields: ctx, example
func (_m *MockUserRepository) ExistsByExample(ctx context.Context, example domain.User) (bool, error) {
	ret := _m.Called(ctx, example)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByExample")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (bool, error)); ok {
		return rf(ctx, example)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) bool); ok {
		r0 = rf(ctx, example)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, example)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_ExistsByExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByExample'
type MockUserRepository_ExistsByExample_Call struct {
	*mock.Call
}

// ExistsByExample is a helper method to define mock.On call
//   - ctx context.Context
//   - example domain.User
func (_e *MockUserRepository_Expecter) ExistsByExample(ctx interface{}, example interface{}) *MockUserRepository_ExistsByExample_Call {
	return &MockUserRepository_ExistsByExample_Call{Call: _e.mock.On("ExistsByExample", ctx, example)}
}

func (_c *MockUserRepository_ExistsByExample_Call) Run(run func(ctx context.Context, example domain.User)) *MockUserRepository_ExistsByExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockUserRepository_ExistsByExample_Call) Return(_a0 bool, _a1 error) *MockUserRepository_ExistsByExample_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_ExistsByExample_Call) RunAndReturn(run func(context.Context, domain.User) (bool, error)) *MockUserRepository_ExistsByExample_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *MockUserRepository) Save(ctx context.Context, _a1 domain.User) (uint, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (uint, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) uint); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 domain.User
func (_e *MockUserRepository_Expecter) Save(ctx interface{}, _a1 interface{}) *MockUserRepository_Save_Call {
	return &MockUserRepository_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *MockUserRepository_Save_Call) Run(run func(ctx context.Context, _a1 domain.User)) *MockUserRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockUserRepository_Save_Call) Return(_a0 uint, _a1 error) *MockUserRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_Save_Call) RunAndReturn(run func(context.Context, domain.User) (uint, error)) *MockUserRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByExample provides a mock function with given fields: ctx, example
func (_m *MockUserRepository) SearchByExample(ctx context.Context, example domain.User) (domain.User, error) {
	ret := _m.Called(ctx, example)

	if len(ret) == 0 {
		panic("no return value specified for SearchByExample")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(ctx, example)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(ctx, example)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, example)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_SearchByExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByExample'
type MockUserRepository_SearchByExample_Call struct {
	*mock.Call
}

// SearchByExample is a helper method to define mock.On call
//   - ctx context.Context
//   - example domain.User
func (_e *MockUserRepository_Expecter) SearchByExample(ctx interface{}, example interface{}) *MockUserRepository_SearchByExample_Call {
	return &MockUserRepository_SearchByExample_Call{Call: _e.mock.On("SearchByExample", ctx, example)}
}

func (_c *MockUserRepository_SearchByExample_Call) Run(run func(ctx context.Context, example domain.User)) *MockUserRepository_SearchByExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockUserRepository_SearchByExample_Call) Return(_a0 domain.User, _a1 error) *MockUserRepository_SearchByExample_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_SearchByExample_Call) RunAndReturn(run func(context.Context, domain.User) (domain.User, error)) *MockUserRepository_SearchByExample_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function with given fields: tx
func (_m *MockUserRepository) WithTransaction(tx persistent.Transaction) domain.UserRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 domain.UserRepository
	if rf, ok := ret.Get(0).(func(persistent.Transaction) domain.UserRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.UserRepository)
		}
	}

	return r0
}

// MockUserRepository_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockUserRepository_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - tx persistent.Transaction
func (_e *MockUserRepository_Expecter) WithTransaction(tx interface{}) *MockUserRepository_WithTransaction_Call {
	return &MockUserRepository_WithTransaction_Call{Call: _e.mock.On("WithTransaction", tx)}
}

func (_c *MockUserRepository_WithTransaction_Call) Run(run func(tx persistent.Transaction)) *MockUserRepository_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(persistent.Transaction))
	})
	return _c
}

func (_c *MockUserRepository_WithTransaction_Call) Return(_a0 domain.UserRepository) *MockUserRepository_WithTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_WithTransaction_Call) RunAndReturn(run func(persistent.Transaction) domain.UserRepository) *MockUserRepository_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
