### Create project
POST http://localhost:8080/api/v1/project/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyIiwiZW1haWwiOiJqY2FhdGFuZWRhZXNwQGdtYWlsLmNvbSIsInN1YiI6IjEiLCJleHAiOjE2ODQ1OTI1MjIsImlhdCI6MTY4NDUwNjEyMn0.pegwkH1D_w3P6-mVbjgHz39k7Hw3c1VLnmAA5xFo3wU

{
    "name": "Test5",
    "userId": 1,
    "type": "budget"
}

### Clone project
POST http://localhost:8080/api/v1/project/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyIiwiZW1haWwiOiJqY2FhdGFuZWRhZXNwQGdtYWlsLmNvbSIsInN1YiI6IjEiLCJleHAiOjE2ODQ1OTI1MjIsImlhdCI6MTY4NDUwNjEyMn0.pegwkH1D_w3P6-mVbjgHz39k7Hw3c1VLnmAA5xFo3wU

{
    "cloneId": 1
}

### Read By User
GET http://localhost:8080/api/v1/project/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyIiwiZW1haWwiOiJqY2FhdGFuZWRhZXNwQGdtYWlsLmNvbSIsInN1YiI6IjEiLCJleHAiOjE2ODQ1OTI1MjIsImlhdCI6MTY4NDUwNjEyMn0.pegwkH1D_w3P6-mVbjgHz39k7Hw3c1VLnmAA5xFo3wU

### Read Logs By Project
GET http://localhost:8080/api/v1/project/logs/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyIiwiZW1haWwiOiJqY2FhdGFuZWRhZXNwQGdtYWlsLmNvbSIsInN1YiI6IjEiLCJleHAiOjE2ODQ1OTI1MjIsImlhdCI6MTY4NDUwNjEyMn0.pegwkH1D_w3P6-mVbjgHz39k7Hw3c1VLnmAA5xFo3wU

### Delete Project
DELETE http://localhost:8080/api/v1/project/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyIiwiZW1haWwiOiJqY2FhdGFuZWRhZXNwQGdtYWlsLmNvbSIsInN1YiI6IjEiLCJleHAiOjE2ODQ1OTI1MjIsImlhdCI6MTY4NDUwNjEyMn0.pegwkH1D_w3P6-mVbjgHz39k7Hw3c1VLnmAA5xFo3wU