### Create User
POST http://localhost:8080/user/
Content-Type: application/json

{
    "uuid": "12345678901234567890123456789012",
    "email": "jcaatanedaesp@gmail.com"
}

### Auth
POST http://localhost:8080/user/auth
Content-Type: application/json

{
    "uuid": "12345678901234567890123456789012",
    "email": "jcaatanedaesp@gmail.com"
}

### RefreshToken
PUT http://localhost:8080/user/refresh-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyIiwiZW1haWwiOiJqY2FhdGFuZWRhZXNwQGdtYWlsLmNvbSIsInN1YiI6IjEiLCJleHAiOjE2ODQ1OTI1MjIsImlhdCI6MTY4NDUwNjEyMn0.pegwkH1D_w3P6-mVbjgHz39k7Hw3c1VLnmAA5xFo3wU",
    "uuid": "12345678901234567890123456789012",
    "email": "jcaatanedaesp@gmail.com"
}