// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "your-accounts-api/budget/domain"

	mock "github.com/stretchr/testify/mock"
)

// IBudgetApp is an autogenerated mock type for the IBudgetApp type
type IBudgetApp struct {
	mock.Mock
}

// FindById provides a mock function with given fields: ctx, id
func (_m *IBudgetApp) FindById(ctx context.Context, id uint) (*domain.Budget, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Budget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Budget, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Budget); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Budget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIBudgetApp interface {
	mock.TestingT
	Cleanup(func())
}

// NewIBudgetApp creates a new instance of IBudgetApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIBudgetApp(t mockConstructorTestingTNewIBudgetApp) *IBudgetApp {
	mock := &IBudgetApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
