// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IProjectApp is an autogenerated mock type for the IProjectApp type
type IProjectApp struct {
	mock.Mock
}

type mockConstructorTestingTNewIProjectApp interface {
	mock.TestingT
	Cleanup(func())
}

// NewIProjectApp creates a new instance of IProjectApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIProjectApp(t mockConstructorTestingTNewIProjectApp) *IProjectApp {
	mock := &IProjectApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
