// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "your-accounts-api/project/domain"

	mock "github.com/stretchr/testify/mock"

	persistent "your-accounts-api/shared/domain/persistent"
)

// IProjectApp is an autogenerated mock type for the IProjectApp type
type IProjectApp struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userId, typeProject, tx
func (_m *IProjectApp) Create(ctx context.Context, userId uint, typeProject domain.ProjectType, tx persistent.Transaction) (uint, error) {
	ret := _m.Called(ctx, userId, typeProject, tx)

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.ProjectType, persistent.Transaction) (uint, error)); ok {
		return rf(ctx, userId, typeProject, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.ProjectType, persistent.Transaction) uint); ok {
		r0 = rf(ctx, userId, typeProject, tx)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, domain.ProjectType, persistent.Transaction) error); ok {
		r1 = rf(ctx, userId, typeProject, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLog provides a mock function with given fields: ctx, description, projectId, detail, tx
func (_m *IProjectApp) CreateLog(ctx context.Context, description string, projectId uint, detail *string, tx persistent.Transaction) error {
	ret := _m.Called(ctx, description, projectId, detail, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, *string, persistent.Transaction) error); ok {
		r0 = rf(ctx, description, projectId, detail, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id, tx
func (_m *IProjectApp) Delete(ctx context.Context, id uint, tx persistent.Transaction) error {
	ret := _m.Called(ctx, id, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, persistent.Transaction) error); ok {
		r0 = rf(ctx, id, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByUserIdAndType provides a mock function with given fields: ctx, userId, typeProject
func (_m *IProjectApp) FindByUserIdAndType(ctx context.Context, userId uint, typeProject domain.ProjectType) ([]uint, error) {
	ret := _m.Called(ctx, userId, typeProject)

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.ProjectType) ([]uint, error)); ok {
		return rf(ctx, userId, typeProject)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.ProjectType) []uint); ok {
		r0 = rf(ctx, userId, typeProject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, domain.ProjectType) error); ok {
		r1 = rf(ctx, userId, typeProject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLogsByProject provides a mock function with given fields: ctx, projectId
func (_m *IProjectApp) FindLogsByProject(ctx context.Context, projectId uint) ([]*domain.ProjectLog, error) {
	ret := _m.Called(ctx, projectId)

	var r0 []*domain.ProjectLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]*domain.ProjectLog, error)); ok {
		return rf(ctx, projectId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []*domain.ProjectLog); ok {
		r0 = rf(ctx, projectId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ProjectLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, projectId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIProjectApp interface {
	mock.TestingT
	Cleanup(func())
}

// NewIProjectApp creates a new instance of IProjectApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIProjectApp(t mockConstructorTestingTNewIProjectApp) *IProjectApp {
	mock := &IProjectApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
