// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "your-accounts-api/shared/domain"

	mock "github.com/stretchr/testify/mock"

	persistent "your-accounts-api/shared/domain/persistent"
)

// ILogApp is an autogenerated mock type for the ILogApp type
type ILogApp struct {
	mock.Mock
}

// CreateLog provides a mock function with given fields: ctx, description, resourceId, detail, tx
func (_m *ILogApp) CreateLog(ctx context.Context, description string, resourceId uint, detail *string, tx persistent.Transaction) error {
	ret := _m.Called(ctx, description, resourceId, detail, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, *string, persistent.Transaction) error); ok {
		r0 = rf(ctx, description, resourceId, detail, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindLogsByProject provides a mock function with given fields: ctx, resourceId
func (_m *ILogApp) FindLogsByProject(ctx context.Context, resourceId uint) ([]*domain.Log, error) {
	ret := _m.Called(ctx, resourceId)

	var r0 []*domain.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]*domain.Log, error)); ok {
		return rf(ctx, resourceId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []*domain.Log); ok {
		r0 = rf(ctx, resourceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, resourceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewILogApp interface {
	mock.TestingT
	Cleanup(func())
}

// NewILogApp creates a new instance of ILogApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewILogApp(t mockConstructorTestingTNewILogApp) *ILogApp {
	mock := &ILogApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
