// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "api-your-accounts/user/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserTokenRepository is an autogenerated mock type for the UserTokenRepository type
type UserTokenRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userToken
func (_m *UserTokenRepository) Create(ctx context.Context, userToken *domain.UserToken) (*domain.UserToken, error) {
	ret := _m.Called(ctx, userToken)

	var r0 *domain.UserToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserToken) (*domain.UserToken, error)); ok {
		return rf(ctx, userToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserToken) *domain.UserToken); ok {
		r0 = rf(ctx, userToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UserToken) error); ok {
		r1 = rf(ctx, userToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserTokenRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserTokenRepository creates a new instance of UserTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserTokenRepository(t mockConstructorTestingTNewUserTokenRepository) *UserTokenRepository {
	mock := &UserTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
