package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"api-your-accounts/shared/infrastructure/graph"
	"api-your-accounts/shared/infrastructure/graph/model"
	"context"
)

// Other is the resolver for the other field.
func (r *helloResolver) Other(ctx context.Context, obj *model.Hello) (*model.Other, error) {
	return &model.Other{
		ID:   "test",
		Name: obj.ID,
	}, nil
}

// Hello returns graph.HelloResolver implementation.
func (r *Resolver) Hello() graph.HelloResolver { return &helloResolver{r} }

type helloResolver struct{ *Resolver }
