package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"api-your-accounts/shared/infrastructure/graph"
	"api-your-accounts/shared/infrastructure/graph/model"
	"context"
)

// Ping is the resolver for the ping field.
func (r *mutationResolver) Ping(ctx context.Context) (*model.Hello, error) {
	return &model.Hello{
		ID: "mutation",
	}, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (*model.Hello, error) {
	return &model.Hello{
		ID: "query",
	}, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
