// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks_persistent

import mock "github.com/stretchr/testify/mock"

// MockTransaction is an autogenerated mock type for the Transaction type
type MockTransaction struct {
	mock.Mock
}

type MockTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransaction) EXPECT() *MockTransaction_Expecter {
	return &MockTransaction_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields:
func (_m *MockTransaction) Get() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockTransaction_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTransaction_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockTransaction_Expecter) Get() *MockTransaction_Get_Call {
	return &MockTransaction_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockTransaction_Get_Call) Run(run func()) *MockTransaction_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransaction_Get_Call) Return(_a0 interface{}) *MockTransaction_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransaction_Get_Call) RunAndReturn(run func() interface{}) *MockTransaction_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: tx
func (_m *MockTransaction) Set(tx interface{}) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransaction_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockTransaction_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - tx interface{}
func (_e *MockTransaction_Expecter) Set(tx interface{}) *MockTransaction_Set_Call {
	return &MockTransaction_Set_Call{Call: _e.mock.On("Set", tx)}
}

func (_c *MockTransaction_Set_Call) Run(run func(tx interface{})) *MockTransaction_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockTransaction_Set_Call) Return(_a0 error) *MockTransaction_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransaction_Set_Call) RunAndReturn(run func(interface{}) error) *MockTransaction_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransaction creates a new instance of MockTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransaction {
	mock := &MockTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
