// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hello struct {
	ID    string `json:"id"`
	Other *Other `json:"other"`
}

type Other struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
