// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Hello struct {
	ID    string `json:"id"`
	Other *Other `json:"other"`
}

type InputUser struct {
	// Longitud 32
	UUID  string `json:"uuid"`
	Email string `json:"email"`
}

type Other struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ProjectLog struct {
	ID          string                 `json:"id"`
	Description string                 `json:"description"`
	Detail      map[string]interface{} `json:"detail"`
	ProjectID   int                    `json:"projectId"`
	CreatedAt   time.Time              `json:"createdAt"`
}

type User struct {
	ID        string     `json:"id"`
	UUID      string     `json:"uuid"`
	Email     string     `json:"email"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
}
