// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hello struct {
	ID    string `json:"id"`
	Other *Other `json:"other"`
}

type InputUser struct {
	// Longitud 32
	UUID  string `json:"uuid"`
	Email string `json:"email"`
}

type Other struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        string  `json:"id"`
	UUID      string  `json:"uuid"`
	Email     string  `json:"email"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt *string `json:"updatedAt"`
}
