// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "your-accounts-api/budgets/domain"

	mock "github.com/stretchr/testify/mock"

	persistent "your-accounts-api/shared/domain/persistent"
)

// BudgetBillRepository is an autogenerated mock type for the BudgetBillRepository type
type BudgetBillRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BudgetBillRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *BudgetBillRepository) Save(ctx context.Context, _a1 domain.BudgetBill) (uint, error) {
	ret := _m.Called(ctx, _a1)

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BudgetBill) (uint, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BudgetBill) uint); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BudgetBill) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAll provides a mock function with given fields: ctx, domains
func (_m *BudgetBillRepository) SaveAll(ctx context.Context, domains []domain.BudgetBill) error {
	ret := _m.Called(ctx, domains)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.BudgetBill) error); ok {
		r0 = rf(ctx, domains)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, id
func (_m *BudgetBillRepository) Search(ctx context.Context, id uint) (*domain.BudgetBill, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.BudgetBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.BudgetBill, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.BudgetBill); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BudgetBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTransaction provides a mock function with given fields: tx
func (_m *BudgetBillRepository) WithTransaction(tx persistent.Transaction) domain.BudgetBillRepository {
	ret := _m.Called(tx)

	var r0 domain.BudgetBillRepository
	if rf, ok := ret.Get(0).(func(persistent.Transaction) domain.BudgetBillRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.BudgetBillRepository)
		}
	}

	return r0
}

type mockConstructorTestingTNewBudgetBillRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBudgetBillRepository creates a new instance of BudgetBillRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBudgetBillRepository(t mockConstructorTestingTNewBudgetBillRepository) *BudgetBillRepository {
	mock := &BudgetBillRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
