### Create
POST http://localhost:8080/api/v1/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk0MDUyOTU5LCJpYXQiOjE2OTM5NjY1NTl9.2qvZgATLWzG48Phy-Z9Ha9qoZNubVK-Ozm0n3Ec7S3w

{
    "name": "Test 05092023-2116"
}

### Clone
POST http://localhost:8080/api/v1/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk0MDUyOTU5LCJpYXQiOjE2OTM5NjY1NTl9.2qvZgATLWzG48Phy-Z9Ha9qoZNubVK-Ozm0n3Ec7S3w

{
    "cloneId": 1
}

### Read
GET http://localhost:8080/api/v1/budget
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk0MDUyOTU5LCJpYXQiOjE2OTM5NjY1NTl9.2qvZgATLWzG48Phy-Z9Ha9qoZNubVK-Ozm0n3Ec7S3w

### Read By ID
GET http://localhost:8080/api/v1/budget/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk0MDUyOTU5LCJpYXQiOjE2OTM5NjY1NTl9.2qvZgATLWzG48Phy-Z9Ha9qoZNubVK-Ozm0n3Ec7S3w

### Delete
DELETE http://localhost:8080/api/v1/budget/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk0MDUyOTU5LCJpYXQiOjE2OTM5NjY1NTl9.2qvZgATLWzG48Phy-Z9Ha9qoZNubVK-Ozm0n3Ec7S3w

### Create Available
POST http://localhost:8080/api/v1/budget/available
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk0MDUyOTU5LCJpYXQiOjE2OTM5NjY1NTl9.2qvZgATLWzG48Phy-Z9Ha9qoZNubVK-Ozm0n3Ec7S3w

{
    "name": "Disponible 1",
    "budgetId": 1
}