### Create
POST http://localhost:8080/api/v1/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjkwNTg0NzA0LCJpYXQiOjE2OTA0OTgzMDR9.OCs_5aaYg-FgO1qBwkLViG-7pGioaNNMzxA1DZIV-_s

{
    "name": "Test 27072023-1752"
}

### Clone
POST http://localhost:8080/api/v1/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjkwNTg0NzA0LCJpYXQiOjE2OTA0OTgzMDR9.OCs_5aaYg-FgO1qBwkLViG-7pGioaNNMzxA1DZIV-_s

{
    "cloneId": 1
}

### Read
GET http://localhost:8080/api/v1/budget
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjkwNTg0NzA0LCJpYXQiOjE2OTA0OTgzMDR9.OCs_5aaYg-FgO1qBwkLViG-7pGioaNNMzxA1DZIV-_s

### Read By ID
GET http://localhost:8080/api/v1/budget/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjkwNTg0NzA0LCJpYXQiOjE2OTA0OTgzMDR9.OCs_5aaYg-FgO1qBwkLViG-7pGioaNNMzxA1DZIV-_s

### Delete
DELETE http://localhost:8080/api/v1/budget/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjkwNTg0NzA0LCJpYXQiOjE2OTA0OTgzMDR9.OCs_5aaYg-FgO1qBwkLViG-7pGioaNNMzxA1DZIV-_s

### Create Available
POST http://localhost:8080/api/v1/budget/available
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjkwNTg0NzA0LCJpYXQiOjE2OTA0OTgzMDR9.OCs_5aaYg-FgO1qBwkLViG-7pGioaNNMzxA1DZIV-_s

{
    "name": "Disponible 1",
    "budgetId": 1
}