### Create
POST http://localhost:8080/api/v1/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk1Nzg0MjIxLCJpYXQiOjE2OTU2OTc4MjF9.gnhFnFtOsidCARJ3XUhknJK0gjKw4iJU8YGKC_OeVYI

{
    "name": "Test 25092023-2210"
}

### Clone
POST http://localhost:8080/api/v1/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk1Nzg0MjIxLCJpYXQiOjE2OTU2OTc4MjF9.gnhFnFtOsidCARJ3XUhknJK0gjKw4iJU8YGKC_OeVYI

{
    "cloneId": 1
}

### Read
GET http://localhost:8080/api/v1/budget
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk1Nzg0MjIxLCJpYXQiOjE2OTU2OTc4MjF9.gnhFnFtOsidCARJ3XUhknJK0gjKw4iJU8YGKC_OeVYI

### Read By ID
GET http://localhost:8080/api/v1/budget/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk1Nzg0MjIxLCJpYXQiOjE2OTU2OTc4MjF9.gnhFnFtOsidCARJ3XUhknJK0gjKw4iJU8YGKC_OeVYI

### Delete
DELETE http://localhost:8080/api/v1/budget/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk1Nzg0MjIxLCJpYXQiOjE2OTU2OTc4MjF9.gnhFnFtOsidCARJ3XUhknJK0gjKw4iJU8YGKC_OeVYI

### Create Available
POST http://localhost:8080/api/v1/budget/available
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidWlkIjoiMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIiLCJlbWFpbCI6ImpjYWF0YW5lZGFlc3BAZ21haWwuY29tIiwiZXhwIjoxNjk1Nzg0MjIxLCJpYXQiOjE2OTU2OTc4MjF9.gnhFnFtOsidCARJ3XUhknJK0gjKw4iJU8YGKC_OeVYI

{
    "name": "Disponible 1",
    "budgetId": 1
}