### Read Logs By Project
GET http://localhost:8080/api/v1/project/logs/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyIiwiZW1haWwiOiJqY2FhdGFuZWRhZXNwQGdtYWlsLmNvbSIsInN1YiI6IjEiLCJleHAiOjE2ODkxMTc1ODEsImlhdCI6MTY4OTAzMTE4MX0.ZU453AzQq-E-5lCqZjkNZt_obBPDKGMcCuSs_eCx9YE